name: coloring_book
description: A kid-friendly coloring book app with photo-to-coloring conversion and AI generation
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  image: ^4.1.3
  image_picker: ^1.0.5
  permission_handler: ^11.2.0
  path_provider: ^2.1.2
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  share_plus: ^7.2.2
  printing: ^5.11.1
  pdf: ^3.10.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/help/
    - .env